theme: hbp

canonifyURLs: false
cleanDestinationDir: true
copyright: Public Domain
defaultContentLanguage: en
metaDataFormat: yaml
noTimes: true
publishDir: public
relativeURLs: true
verbose: false
watch: true
disableKinds:
    - RSS
    - taxonomy
    - taxonomyTerm
minify:
    minifyOutput: true
    tdewolff:
        html:
            keepConditionalComments: false
            keepQuotes: true

languages:
    en:
        languageCode: en-us
        languageLang: en
        languageName: English
        weight: 0

####################################################################################################
baseURL: https://iinf.in/
title: iinfin (@u29dc)

params:
    resources:
        fingerprint: false
        inline: false

    description: ⧜
    email: #
    license: https://creativecommons.org/publicdomain/zero/1.0
    src: https://github.com/u29dc/www
    username: u29dc

    links:
        about: https://about.me/u29dc
        angel: https://angel.co/u29dc
        artstation: https://artstation.com/u29dc
        bandcamp: https://u29dc.bandcamp.com
        behance: https://behance.net/u29dc
        dribbble: https://dribbble.com/u29dc
        ello: https://ello.co/u29dc
        flickr: https://flickr.com/u29dc
        github: https://github.com/u29dc
        gitlab: https://gitlab.com/u29dc
        goodreads: https://goodreads.com/u29dc
        instagram: https://instagram.com/u29dc
        keybase: https://keybase.io/u29dc
        linkedin: https://linkedin.com/company/u29dc
        medium: https://medium.com/u29dc
        pgp: https://iinf.in/pgp
        pinterest: https://pinterest.com/u29dc
        reddit: https://reddit.com/u/u29dc
        soundcloud: https://soundcloud.com/u29dc
        tumblr: https://u29dc.tumblr.com
        twitch: https://twitch.tv/u29dc
        twitter: https://twitter.com/u29dc
        unsplash: https://unsplash.com/u29dc
        vimeo: https://vimeo.com/u29dc
