[Settings]

# build settings
##################################################
[build]
  command = "npm run theme && npm run build"
  publish = "public/"

# build environment
[build.environment]
  HUGO_VERSION = "0.74.1"
  NODE_VERSION = "14.5.0"

# build processing
[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = false

# redirects
##################################################
[[redirects]]
  from = "https://u29dc.netlify.app/*"
  to = "https://iinf.in/:splat"
  status = 301
  force = true

# pgp key
[[redirects]]
  from = "/pgp"
  status = 301
  to = "https://keybase.io/u29dc/pgp_keys.asc"

# headers
##################################################
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
        base-uri 'self';
        default-src 'none';
        font-src 'self' cdn.jsdelivr.net;
        form-action 'self';
        frame-ancestors 'none';
        frame-src 'self';
        img-src 'self' data:;
        manifest-src 'self';
        media-src 'self';
        object-src 'none';
        script-src 'self' cdn.jsdelivr.net;
        style-src 'self' cdn.jsdelivr.net;
        upgrade-insecure-requests;
    """
    Expect-CT = "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""
    Feature-Policy = """
        accelerometer 'self';
        ambient-light-sensor 'self';
        autoplay 'self';
        camera 'self';
        document-domain 'self';
        encrypted-media 'self';
        fullscreen 'self';
        geolocation 'self';
        gyroscope 'self';
        magnetometer 'self';
        microphone 'self';
        midi 'self';
        payment 'self';
        picture-in-picture 'self';
        speaker 'self';
        sync-xhr 'self';
        usb 'self';
        vr / xr 'self';
    """
    Referrer-Policy = "strict-origin"
    Strict-Transport-Security = "max-age=31557600; includesubdomains; preload"
    Vary = "Accept-Encoding"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"
